/****************************************************************************
**
** Metadata for XA_SESSIONLib generated by dumpcpp v5.5.1 using
** dumpcpp.exe C:\eBEST\xingAPI\XA_Session.dll
** from the type library C:\eBEST\xingAPI\XA_Session.dll
**
****************************************************************************/

#define QAX_DUMPCPP_XA_SESSIONLIB_NOINLINES
#include "xa_sessionlib.h"

using namespace XA_SESSIONLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[62];
    char stringdata0[731];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 24, 0),
QT_MOC_LITERAL(1, 25, 17, 0),
QT_MOC_LITERAL(2, 43, 17, 0),
QT_MOC_LITERAL(3, 61, 11, 0),
QT_MOC_LITERAL(4, 73, 10, 0),
QT_MOC_LITERAL(5, 84, 10, 0),
QT_MOC_LITERAL(6, 95, 0, 0),
QT_MOC_LITERAL(7, 96, 5, 0),
QT_MOC_LITERAL(8, 102, 6, 0),
QT_MOC_LITERAL(9, 109, 5, 0),
QT_MOC_LITERAL(10, 115, 6, 0),
QT_MOC_LITERAL(11, 122, 9, 0),
QT_MOC_LITERAL(12, 132, 4, 0),
QT_MOC_LITERAL(13, 137, 6, 0),
QT_MOC_LITERAL(14, 144, 4, 0),
QT_MOC_LITERAL(15, 149, 4, 0),
QT_MOC_LITERAL(16, 154, 15, 0),
QT_MOC_LITERAL(17, 170, 4, 0),
QT_MOC_LITERAL(18, 175, 6, 0),
QT_MOC_LITERAL(19, 182, 4, 0),
QT_MOC_LITERAL(20, 187, 4, 0),
QT_MOC_LITERAL(21, 192, 13, 0),
QT_MOC_LITERAL(22, 206, 10, 0),
QT_MOC_LITERAL(23, 217, 11, 0),
QT_MOC_LITERAL(24, 229, 16, 0),
QT_MOC_LITERAL(25, 246, 14, 0),
QT_MOC_LITERAL(26, 261, 6, 0),
QT_MOC_LITERAL(27, 268, 19, 0),
QT_MOC_LITERAL(28, 288, 14, 0),
QT_MOC_LITERAL(29, 303, 5, 0),
QT_MOC_LITERAL(30, 309, 17, 0),
QT_MOC_LITERAL(31, 327, 15, 0),
QT_MOC_LITERAL(32, 343, 11, 0),
QT_MOC_LITERAL(33, 355, 12, 0),
QT_MOC_LITERAL(34, 368, 11, 0),
QT_MOC_LITERAL(35, 380, 15, 0),
QT_MOC_LITERAL(36, 396, 10, 0),
QT_MOC_LITERAL(37, 407, 12, 0),
QT_MOC_LITERAL(38, 420, 7, 0),
QT_MOC_LITERAL(39, 428, 13, 0),
QT_MOC_LITERAL(40, 442, 11, 0),
QT_MOC_LITERAL(41, 454, 9, 0),
QT_MOC_LITERAL(42, 464, 4, 0),
QT_MOC_LITERAL(43, 469, 5, 0),
QT_MOC_LITERAL(44, 475, 9, 0),
QT_MOC_LITERAL(45, 485, 11, 0),
QT_MOC_LITERAL(46, 497, 15, 0),
QT_MOC_LITERAL(47, 513, 17, 0),
QT_MOC_LITERAL(48, 531, 14, 0),
QT_MOC_LITERAL(49, 546, 7, 0),
QT_MOC_LITERAL(50, 554, 6, 0),
QT_MOC_LITERAL(51, 561, 17, 0),
QT_MOC_LITERAL(52, 579, 14, 0),
QT_MOC_LITERAL(53, 594, 13, 0),
QT_MOC_LITERAL(54, 608, 9, 0),
QT_MOC_LITERAL(55, 618, 10, 0),
QT_MOC_LITERAL(56, 629, 14, 0),
QT_MOC_LITERAL(57, 644, 20, 0),
QT_MOC_LITERAL(58, 665, 14, 0),
QT_MOC_LITERAL(59, 680, 15, 0),
QT_MOC_LITERAL(60, 696, 25, 0),
QT_MOC_LITERAL(61, 722, 7, 0)
    },
    "XA_SESSIONLib::XASession\0Event Interface 1\0_IXASessionEvents\0Interface 0\0"
    "IXASession\0Disconnect\0\0Login\0szCode\0szMsg\0Logout\0exception\0code\0source\0disc\0"
    "help\0propertyChanged\0name\0signal\0argc\0argv\0ConnectServer\0szServerIP\0nServerPort\0"
    "DisconnectServer\0GetAccountList\0nIndex\0GetAccountListCount\0GetAccountName\0"
    "szAcc\0GetAcctDetailName\0GetAcctNickname\0GetClientIP\0GetCommMedia\0GetETKMedia\0"
    "GetErrorMessage\0nErrorCode\0GetLastError\0GetPath\0GetServerName\0IsConnected\0"
    "IsLoadAPI\0szID\0szPwd\0szCertPwd\0nServerType\0bShowCertErrDlg\0SetConnectTimeOut\0"
    "ConnectTimeOut\0SetPath\0szPath\0SetSendPacketSize\0SendPacketSize\0XA_MESSAGE_ID\0"
    "XA_FAILED\0XA_SUCCESS\0XA_SERVER_TYPE\0XA_NOSELECTED_SERVER\0XA_REAL_SERVER\0"
    "XA_SIMUL_SERVER\0XA_SESSIONLib::IXASession\0control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_XA_SESSIONLib__XASession[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    27, 18, // methods
    2, 230, // properties
    2, 236, // enums/sets
    0, 0, // constructors
    0, // flags
    6, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 0, 153, 6, 5,
    7, 2, 154, 6, 5,
    10, 0, 159, 6, 5,
    11, 4, 160, 6, 5,
    16, 1, 169, 6, 5,
    18, 3, 172, 6, 5,

// slot: name, argc, parameters, tag, flags
    21, 2, 179, 6, 9,
    24, 0, 184, 6, 9,
    25, 1, 185, 6, 9,
    27, 0, 188, 6, 9,
    28, 1, 189, 6, 9,
    30, 1, 192, 6, 9,
    31, 1, 195, 6, 9,
    32, 0, 198, 6, 9,
    33, 0, 199, 6, 9,
    34, 0, 200, 6, 9,
    35, 1, 201, 6, 9,
    37, 0, 204, 6, 9,
    38, 0, 205, 6, 9,
    39, 0, 206, 6, 9,
    40, 0, 207, 6, 9,
    41, 0, 208, 6, 9,
    7, 5, 209, 6, 9,
    10, 0, 220, 6, 9,
    47, 1, 221, 6, 9,
    49, 1, 224, 6, 9,
    51, 1, 227, 6, 9,

// signal: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 8, 9,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 12, 13, 14, 15,
    QMetaType::Void, QMetaType::QString, 17,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 17, 19, 20,

// slot: parameters
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, 22, 23,
    QMetaType::Void,
    QMetaType::QString, QMetaType::Int, 26,
    QMetaType::Int,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 36,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Bool, 42, 43, 44, 45, 46,
    QMetaType::Bool,
    QMetaType::Void, QMetaType::Int, 48,
    QMetaType::Void, QMetaType::QString, 50,
    QMetaType::Void, QMetaType::Int, 52,

 // properties: name, type, flags
    48, QMetaType::Int, 0x02015003, 		 // int ConnectTimeOut
    52, QMetaType::Int, 0x02015003, 		 // int SendPacketSize

 // enums: name, flags, count, data
    53, 0x0, 2, 244, 
    56, 0x0, 3, 248, 

 // enum data: key, value
    54, uint(XA_SESSIONLib::XA_FAILED),
    55, uint(XA_SESSIONLib::XA_SUCCESS),
    57, uint(XA_SESSIONLib::XA_NOSELECTED_SERVER),
    58, uint(XA_SESSIONLib::XA_REAL_SERVER),
    59, uint(XA_SESSIONLib::XA_SIMUL_SERVER),
    0 // eod
};

const QMetaObject XASession::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_XA_SESSIONLib__XASession, 0, 0, 0 }
};

void *XASession::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "XA_SESSIONLib::XASession"))
        return static_cast<void*>(const_cast<XASession*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_XA_SESSIONLib__IXASession[] = {

 // content:
    7, // revision
    60,  // classname
    0, 0, // classinfo
    24, 14, // methods
    3, 204, // properties
    2, 213, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    11, 4, 134, 6, 5,
    16, 1, 143, 6, 5,
    18, 3, 146, 6, 5,

// slot: name, argc, parameters, tag, flags
    21, 2, 153, 6, 9,
    24, 0, 158, 6, 9,
    25, 1, 159, 6, 9,
    27, 0, 162, 6, 9,
    28, 1, 163, 6, 9,
    30, 1, 166, 6, 9,
    31, 1, 169, 6, 9,
    32, 0, 172, 6, 9,
    33, 0, 173, 6, 9,
    34, 0, 174, 6, 9,
    35, 1, 175, 6, 9,
    37, 0, 178, 6, 9,
    38, 0, 179, 6, 9,
    39, 0, 180, 6, 9,
    40, 0, 181, 6, 9,
    41, 0, 182, 6, 9,
    7, 5, 183, 6, 9,
    10, 0, 194, 6, 9,
    47, 1, 195, 6, 9,
    49, 1, 198, 6, 9,
    51, 1, 201, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 12, 13, 14, 15,
    QMetaType::Void, QMetaType::QString, 17,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 17, 19, 20,

// slot: parameters
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, 22, 23,
    QMetaType::Void,
    QMetaType::QString, QMetaType::Int, 26,
    QMetaType::Int,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 36,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Bool, 42, 43, 44, 45, 46,
    QMetaType::Bool,
    QMetaType::Void, QMetaType::Int, 48,
    QMetaType::Void, QMetaType::QString, 50,
    QMetaType::Void, QMetaType::Int, 52,

 // properties: name, type, flags
    48, QMetaType::Int, 0x02015003, 		 // int ConnectTimeOut
    52, QMetaType::Int, 0x02015003, 		 // int SendPacketSize
    61, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    53, 0x0, 2, 221, 
    56, 0x0, 3, 225, 

 // enum data: key, value
    54, uint(XA_SESSIONLib::XA_FAILED),
    55, uint(XA_SESSIONLib::XA_SUCCESS),
    57, uint(XA_SESSIONLib::XA_NOSELECTED_SERVER),
    58, uint(XA_SESSIONLib::XA_REAL_SERVER),
    59, uint(XA_SESSIONLib::XA_SIMUL_SERVER),
    0 // eod
};

const QMetaObject IXASession::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_XA_SESSIONLib__IXASession, 0, 0, 0 }
};

void *IXASession::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "XA_SESSIONLib::IXASession"))
        return static_cast<void*>(const_cast<IXASession*>(this));
    return QAxObject::qt_metacast(_clname);
}

